import type { StudyModelConfig } from "./StudyModel";
import * as THREE from "three";

export const studyModelConfigs = {
  briefcase: {
    src: "/models/study/briefcase.glb",
    enabled: true,
    targetHeight: 1.2,
    anchor: "top",
    scale: 1.5,
    position: [2.68, 0.5, 0],
    rotation: [0, Math.PI / 2, 0],
    castShadow: true,
    receiveShadow: true,
  },
  chair: {
    src: "/models/study/chair.glb",
    enabled: true,
    targetHeight: 4.6,
    anchor: "bottom",
    position: [-1.8, -2.08, 2.05],
    rotation: [0, Math.PI - THREE.MathUtils.degToRad(20), 0],
    castShadow: true,
    receiveShadow: true,
  },
  chairPad: {
    src: "/models/study/chair-pad.glb",
    enabled: true,
    targetHeight: 0.22,
    anchor: "bottom",
    scale: 2,
    // Measured seat center and top surface; rug lift is inherited from the parent.
    position: [-1.8, 0.501, 2.05],
    rotation: [0, Math.PI - THREE.MathUtils.degToRad(35), 0],
    castShadow: true,
    receiveShadow: true,
  },
  schoolBag: {
    src: "/models/study/pink-school-bag.glb",
    enabled: true,
    targetHeight: 1.35,
    anchor: "bottom",
    scale: 1.77,
    position: [0.96, -2.08, 1.68],
    rotation: [0, Math.PI / 2 - THREE.MathUtils.degToRad(30), 0],
    castShadow: true,
    receiveShadow: true,
  },
  desk: {
    src: "/models/study/desk.glb",
    enabled: true,
    targetHeight: 6.6,
    anchor: "bottom",
    position: [0, -2.92, 0],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  printer: {
    src: "/models/study/printer.glb",
    enabled: true,
    targetHeight: 1.1,
    anchor: "bottom",
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  laptop: {
    src: "/models/study/laptop.glb",
    enabled: true,
    targetHeight: 1,
    anchor: "bottom",
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  phone: {
    src: "/models/study/flip-phone-white.glb",
    enabled: true,
    targetHeight: 1,
    anchor: "bottom",
    scale: 0.3,
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  book: {
    src: "/models/study/book.glb",
    enabled: true,
    targetHeight: 0.2,
    anchor: "bottom",
    position: [0.1, 0.49, 0],
    rotation: [0, 0.1, 0],
    castShadow: true,
    receiveShadow: true,
  },
  book2: {
    src: "/models/study/star-book.glb",
    enabled: true,
    targetHeight: 0.82,
    anchor: "bottom",
    scale: 1.5,
    position: [-0.06, 2.92, -1.21],
    rotation: [
      -THREE.MathUtils.degToRad(12),
      0,
      -THREE.MathUtils.degToRad(7),
    ],
    castShadow: true,
    receiveShadow: true,
  },
  notebooks: {
    src: "/models/study/book3.glb",
    enabled: true,
    targetHeight: 0.78,
    anchor: "bottom",
    scale: 1.5,
    position: [1.55, 2.91, -1],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  teddybear: {
    src: "/models/study/teddybear-yellow.glb",
    enabled: true,
    targetHeight: 0.78,
    anchor: "bottom",
    scale: 1.7,
    position: [-1.6, 2.95, -1.2],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  curtain: {
    src: "/models/study/curtain.glb",
    enabled: true,
    targetHeight: 2.25,
    anchor: "bottom",
    scale: 3.05,
    position: [0, -4.3, -0.07],
    rotation: [0, Math.PI, 0],
    castShadow: true,
    receiveShadow: true,
    doubleSided: true,
  },
  pencilCase: {
    src: "/models/study/pencil-case.glb",
    enabled: true,
    targetHeight: 0.32,
    anchor: "bottom",
    scale: 0.8,
    position: [0.14, 0.65, 0],
    rotation: [0, Math.PI / 2 + THREE.MathUtils.degToRad(40), 0],
    castShadow: true,
    receiveShadow: true,
  },
  lamp: {
    src: "/models/study/lamp.glb",
    enabled: true,
    targetHeight: 0.9,
    anchor: "bottom",
    scale: 1.5,
    position: [-1.18, 0.65, -0.9],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  oldBook: {
    src: "/models/study/old-book.glb",
    enabled: true,
    targetHeight: 0.45,
    anchor: "bottom",
    scale: 0.47,
    position: [-0.45, 0.65, -0.96],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  dessert: {
    src: "/models/study/dessert.glb",
    enabled: true,
    targetHeight: 0.6,
    anchor: "bottom",
    scale: 1.5,
    position: [-0.28, 0.88, -0.96],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  pen: {
    src: "/models/study/pen.glb",
    enabled: true,
    targetHeight: 0.05,
    anchor: "bottom",
    position: [0.64, 0.86, 0.95],
    rotation: [0, Math.PI / 2 + THREE.MathUtils.degToRad(65), Math.PI / 2],
    castShadow: true,
    receiveShadow: true,
  },
  pencilBox: {
    src: "/models/study/pencil-box.glb",
    enabled: true,
    targetHeight: 0.42,
    anchor: "bottom",
    scale: [2.52, 2.1, 2.1],
    position: [1.32, 1.6, -0.86],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  clothHandler: {
    src: "/models/study/cloth-handler.glb",
    enabled: true,
    targetHeight: 0.55,
    anchor: "bottom",
    scale: 1.2,
    position: [-0.2, 0, 0],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  umbrella: {
    src: "/models/study/umbrella.glb",
    enabled: true,
    targetHeight: 1.65,
    anchor: "top",
    scale: 1.9,
    position: [0.42, 0.27, 0.06],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  idBag: {
    src: "/models/study/id-bag.glb",
    enabled: true,
    targetHeight: 1.1,
    anchor: "center",
    scale: 0.9,
    position: [-0.45, -0.18, 0.3],
    // Rotate within the wall plane: the strap points up and the front stays outward.
    rotation: [Math.PI / 2, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  bookStackFloor: {
    src: "/models/study/book-stack.glb",
    enabled: true,
    targetHeight: 0.6,
    anchor: "bottom",
    scale: 1.1,
    position: [-2.3, -2.08, -1.95],
    rotation: [0, Math.PI / 2, 0],
    castShadow: true,
    receiveShadow: true,
  },
  rug: {
    src: "/models/study/rug.glb",
    enabled: true,
    materialBrightness: 0.8,
    targetHeight: 0.03,
    anchor: "bottom",
    // Expand the footprint without thickening the carpet or lifting furniture excessively.
    scale: [1.25, 1, 1.845],
    position: [0.14, -2.08, 0.05],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
} satisfies Record<string, StudyModelConfig>;
