import type { StudyModelConfig } from "./StudyModel";
import * as THREE from "three";

export const studyModelConfigs = {
  briefcase: {
    src: "/models/study/briefcase.glb",
    enabled: true,
    targetHeight: 1.2,
    anchor: "top",
    position: [2.68, -0.5, 0],
    rotation: [0, Math.PI / 2, 0],
    castShadow: true,
    receiveShadow: true,
  },
  chair: {
    src: "/models/study/chair.glb",
    enabled: true,
    targetHeight: 4.6,
    anchor: "bottom",
    position: [-1.8, -2.08, 2.05],
    rotation: [0, Math.PI - THREE.MathUtils.degToRad(20), 0],
    castShadow: true,
    receiveShadow: true,
  },
  desk: {
    src: "/models/study/desk.glb",
    enabled: true,
    targetHeight: 6.6,
    anchor: "bottom",
    position: [0, -2.92, 0],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  laptop: {
    src: "/models/study/laptop.glb",
    enabled: true,
    targetHeight: 1,
    anchor: "bottom",
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  book: {
    src: "/models/study/book.glb",
    enabled: true,
    targetHeight: 0.2,
    anchor: "bottom",
    position: [0.1, 0.49, 0],
    rotation: [0, 0.1, 0],
    castShadow: true,
    receiveShadow: true,
  },
  book2: {
    src: "/models/study/book2.glb",
    enabled: true,
    targetHeight: 0.82,
    anchor: "bottom",
    scale: 1.5,
    position: [-0.06, 2.87, -1.21],
    rotation: [
      -THREE.MathUtils.degToRad(12),
      0,
      -THREE.MathUtils.degToRad(7),
    ],
    castShadow: true,
    receiveShadow: true,
  },
  notebooks: {
    src: "/models/study/notebooks.glb",
    enabled: true,
    targetHeight: 0.78,
    anchor: "bottom",
    scale: 1.5,
    position: [1.55, 2.87, -1.2],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  teddybear: {
    src: "/models/study/teddybear.glb",
    enabled: true,
    targetHeight: 0.78,
    anchor: "bottom",
    scale: 1.7,
    position: [-1.75, 2.93, -1.2],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  curtain: {
    src: "/models/study/curtain.glb",
    enabled: true,
    targetHeight: 2.25,
    anchor: "bottom",
    scale: 3.05,
    position: [0, -4.3, -0.07],
    rotation: [0, Math.PI, 0],
    castShadow: true,
    receiveShadow: true,
    doubleSided: true,
  },
  pencilCase: {
    src: "/models/study/pencil-case.glb",
    enabled: true,
    targetHeight: 0.32,
    anchor: "bottom",
    scale: 0.8,
    position: [0.14, 0.65, 0],
    rotation: [0, Math.PI / 2 + THREE.MathUtils.degToRad(40), 0],
    castShadow: true,
    receiveShadow: true,
  },
  lamp: {
    src: "/models/study/lamp.glb",
    enabled: true,
    targetHeight: 0.9,
    anchor: "bottom",
    scale: 1.5,
    position: [-1.18, 0.65, -0.9],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  oldBook: {
    src: "/models/study/old-book.glb",
    enabled: true,
    targetHeight: 0.45,
    anchor: "bottom",
    scale: 0.47,
    position: [-0.45, 0.65, -0.96],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  pen: {
    src: "/models/study/pen.glb",
    enabled: true,
    targetHeight: 0.05,
    anchor: "bottom",
    position: [0.64, 0.86, 0.95],
    rotation: [0, Math.PI / 2 + THREE.MathUtils.degToRad(65), Math.PI / 2],
    castShadow: true,
    receiveShadow: true,
  },
  pencilBox: {
    src: "/models/study/pencil-box.glb",
    enabled: true,
    targetHeight: 0.42,
    anchor: "bottom",
    scale: [2.52, 2.1, 2.1],
    position: [1.32, 1.6, -0.86],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
  clothHandler: {
    src: "/models/study/cloth-handler.glb",
    enabled: true,
    targetHeight: 0.55,
    anchor: "bottom",
    scale: 1.2,
    position: [-0.2, 0, 0],
    rotation: [0, 0, 0],
    castShadow: true,
    receiveShadow: true,
  },
} satisfies Record<string, StudyModelConfig>;
